//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMilk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMilk.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutAppbar {
            get {
                return ResourceManager.GetString("AboutAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string AddTaskAppbar {
            get {
                return ResourceManager.GetString("AddTaskAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddTasksButton {
            get {
                return ResourceManager.GetString("AddTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        public static string AdvancedTaskAddLink {
            get {
                return ResourceManager.GetString("AdvancedTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllTasksHeader {
            get {
                return ResourceManager.GetString("AllTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinMilk.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINMILK.
        /// </summary>
        public static string AppNameCaps {
            get {
                return ResourceManager.GetString("AppNameCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winmilk.
        /// </summary>
        public static string AppNameLower {
            get {
                return ResourceManager.GetString("AppNameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTaskAddLink {
            get {
                return ResourceManager.GetString("CancelTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string LogoutAppbar {
            get {
                return ResourceManager.GetString("LogoutAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsAppbar {
            get {
                return ResourceManager.GetString("SettingsAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncAppbar {
            get {
                return ResourceManager.GetString("SyncAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayTasksHeader {
            get {
                return ResourceManager.GetString("TodayTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string TomorrowTasksHeader {
            get {
                return ResourceManager.GetString("TomorrowTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        public static string WeekTasksHeader {
            get {
                return ResourceManager.GetString("WeekTasksHeader", resourceCulture);
            }
        }
    }
}
