//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMilk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMilk.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juliana Peña.
        /// </summary>
        public static string AboutAuthorLink {
            get {
                return ResourceManager.GetString("AboutAuthorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a cup of coffee!.
        /// </summary>
        public static string AboutCoffeeLink {
            get {
                return ResourceManager.GetString("AboutCoffeeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like this app?.
        /// </summary>
        public static string AboutCoffeePrompt {
            get {
                return ResourceManager.GetString("AboutCoffeePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string AboutCreatedBy {
            get {
                return ResourceManager.GetString("AboutCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses the Remember The Milk API but is not endorsed or certified by Remember The Milk..
        /// </summary>
        public static string AboutDisclaimer {
            get {
                return ResourceManager.GetString("AboutDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string AboutOK {
            get {
                return ResourceManager.GetString("AboutOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageHeader {
            get {
                return ResourceManager.GetString("AboutPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug or suggest a feature.
        /// </summary>
        public static string AboutReport {
            get {
                return ResourceManager.GetString("AboutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review this app.
        /// </summary>
        public static string AboutReview {
            get {
                return ResourceManager.GetString("AboutReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Remember the Milk.
        /// </summary>
        public static string AboutRTMLink {
            get {
                return ResourceManager.GetString("AboutRTMLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.2.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit WinMilk&apos;s site.
        /// </summary>
        public static string AboutVisitSite {
            get {
                return ResourceManager.GetString("AboutVisitSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string AddTaskAppbar {
            get {
                return ResourceManager.GetString("AddTaskAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string AddTaskDue {
            get {
                return ResourceManager.GetString("AddTaskDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string AddTaskDueDay {
            get {
                return ResourceManager.GetString("AddTaskDueDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string AddTaskDueNever {
            get {
                return ResourceManager.GetString("AddTaskDueNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string AddTaskDueTime {
            get {
                return ResourceManager.GetString("AddTaskDueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string AddTaskList {
            get {
                return ResourceManager.GetString("AddTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddTaskName {
            get {
                return ResourceManager.GetString("AddTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string AddTaskPriority {
            get {
                return ResourceManager.GetString("AddTaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AddTaskPriorityNone {
            get {
                return ResourceManager.GetString("AddTaskPriorityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddTasksButton {
            get {
                return ResourceManager.GetString("AddTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string AddTaskTags {
            get {
                return ResourceManager.GetString("AddTaskTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string AddTaskTitle {
            get {
                return ResourceManager.GetString("AddTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced....
        /// </summary>
        public static string AdvancedTaskAddLink {
            get {
                return ResourceManager.GetString("AdvancedTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinMilk.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINMILK.
        /// </summary>
        public static string AppNameCaps {
            get {
                return ResourceManager.GetString("AppNameCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winmilk.
        /// </summary>
        public static string AppNameLower {
            get {
                return ResourceManager.GetString("AppNameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AuthDoneButton {
            get {
                return ResourceManager.GetString("AuthDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After logging in and authorizing the app, tap the done button.
        /// </summary>
        public static string AuthInstructions {
            get {
                return ResourceManager.GetString("AuthInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string AuthPageTitle {
            get {
                return ResourceManager.GetString("AuthPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string AuthRetryButton {
            get {
                return ResourceManager.GetString("AuthRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTaskAddLink {
            get {
                return ResourceManager.GetString("CancelTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string EditTaskSaveButton {
            get {
                return ResourceManager.GetString("EditTaskSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit task.
        /// </summary>
        public static string EditTaskTitle {
            get {
                return ResourceManager.GetString("EditTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST.
        /// </summary>
        public static string ListPageTitle {
            get {
                return ResourceManager.GetString("ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        public static string ListsHeader {
            get {
                return ResourceManager.GetString("ListsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in and authorize the app before continuing.
        /// </summary>
        public static string LogInMessageBoxText {
            get {
                return ResourceManager.GetString("LogInMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to WinMilk!.
        /// </summary>
        public static string LogInMessageBoxTitle {
            get {
                return ResourceManager.GetString("LogInMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out and erase your settings?.
        /// </summary>
        public static string LogOutMessageBoxText {
            get {
                return ResourceManager.GetString("LogOutMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutMessageBoxTitle {
            get {
                return ResourceManager.GetString("LogOutMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MoreAboutButton {
            get {
                return ResourceManager.GetString("MoreAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string MoreActionsHeader {
            get {
                return ResourceManager.GetString("MoreActionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate.
        /// </summary>
        public static string MoreDonateButton {
            get {
                return ResourceManager.GetString("MoreDonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string MoreLogoutButton {
            get {
                return ResourceManager.GetString("MoreLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report bug or suggest feature.
        /// </summary>
        public static string MoreReportButton {
            get {
                return ResourceManager.GetString("MoreReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MoreSearchButton {
            get {
                return ResourceManager.GetString("MoreSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MoreSettingsButton {
            get {
                return ResourceManager.GetString("MoreSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string MoreTagsButton {
            get {
                return ResourceManager.GetString("MoreTagsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no due.
        /// </summary>
        public static string NoDueTasksHeader {
            get {
                return ResourceManager.GetString("NoDueTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueTasksHeader {
            get {
                return ResourceManager.GetString("OverdueTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to hub.
        /// </summary>
        public static string PinAppbar {
            get {
                return ResourceManager.GetString("PinAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchPageHeader {
            get {
                return ResourceManager.GetString("SearchPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eg: pick up the milk today !1 #personal.
        /// </summary>
        public static string SmartAddExample {
            get {
                return ResourceManager.GetString("SmartAddExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smart add.
        /// </summary>
        public static string SmartAddHeader {
            get {
                return ResourceManager.GetString("SmartAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncAppbar {
            get {
                return ResourceManager.GetString("SyncAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG.
        /// </summary>
        public static string TagPageTitle {
            get {
                return ResourceManager.GetString("TagPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string TagsHeader {
            get {
                return ResourceManager.GetString("TagsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string TaskCompleteButton {
            get {
                return ResourceManager.GetString("TaskCompleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string TaskDeleteButton {
            get {
                return ResourceManager.GetString("TaskDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this task permanently?.
        /// </summary>
        public static string TaskDeleteConfirmText {
            get {
                return ResourceManager.GetString("TaskDeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        public static string TaskDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("TaskDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskDetailsHeader {
            get {
                return ResourceManager.GetString("TaskDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string TaskEditButton {
            get {
                return ResourceManager.GetString("TaskEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string TaskListDetail {
            get {
                return ResourceManager.GetString("TaskListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string TaskNotesAddButton {
            get {
                return ResourceManager.GetString("TaskNotesAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string TaskNotesDeleteButton {
            get {
                return ResourceManager.GetString("TaskNotesDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string TaskNotesEditButton {
            get {
                return ResourceManager.GetString("TaskNotesEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string TaskNotesHeader {
            get {
                return ResourceManager.GetString("TaskNotesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postpone.
        /// </summary>
        public static string TaskPostponeButton {
            get {
                return ResourceManager.GetString("TaskPostponeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string TaskShareDue {
            get {
                return ResourceManager.GetString("TaskShareDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share as email.
        /// </summary>
        public static string TaskShareEmailButton {
            get {
                return ResourceManager.GetString("TaskShareEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string TaskShareList {
            get {
                return ResourceManager.GetString("TaskShareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share as message.
        /// </summary>
        public static string TaskShareMessageButton {
            get {
                return ResourceManager.GetString("TaskShareMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TaskShareNotes {
            get {
                return ResourceManager.GetString("TaskShareNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TaskShareTags {
            get {
                return ResourceManager.GetString("TaskShareTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskShareTask {
            get {
                return ResourceManager.GetString("TaskShareTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string TaskShareUrl {
            get {
                return ResourceManager.GetString("TaskShareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TasksHeader {
            get {
                return ResourceManager.GetString("TasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TaskTagsDetail {
            get {
                return ResourceManager.GetString("TaskTagsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string TaskURLDetail {
            get {
                return ResourceManager.GetString("TaskURLDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string TaskWhenDetail {
            get {
                return ResourceManager.GetString("TaskWhenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayTasksHeader {
            get {
                return ResourceManager.GetString("TodayTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string TomorrowTasksHeader {
            get {
                return ResourceManager.GetString("TomorrowTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later this week.
        /// </summary>
        public static string WeekTasksHeader {
            get {
                return ResourceManager.GetString("WeekTasksHeader", resourceCulture);
            }
        }
    }
}
