//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMilk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMilk.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add task.
        /// </summary>
        public static string AddTaskAppbar {
            get {
                return ResourceManager.GetString("AddTaskAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddTasksButton {
            get {
                return ResourceManager.GetString("AddTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        public static string AdvancedTaskAddLink {
            get {
                return ResourceManager.GetString("AdvancedTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinMilk.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINMILK.
        /// </summary>
        public static string AppNameCaps {
            get {
                return ResourceManager.GetString("AppNameCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winmilk.
        /// </summary>
        public static string AppNameLower {
            get {
                return ResourceManager.GetString("AppNameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AuthDoneButton {
            get {
                return ResourceManager.GetString("AuthDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After authenticating and authorizing the app, tap the done button.
        /// </summary>
        public static string AuthInstructions {
            get {
                return ResourceManager.GetString("AuthInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authenticate.
        /// </summary>
        public static string AuthPageTitle {
            get {
                return ResourceManager.GetString("AuthPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTaskAddLink {
            get {
                return ResourceManager.GetString("CancelTaskAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        public static string ListsHeader {
            get {
                return ResourceManager.GetString("ListsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MoreAboutButton {
            get {
                return ResourceManager.GetString("MoreAboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string MoreActionsHeader {
            get {
                return ResourceManager.GetString("MoreActionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string MoreLogoutButton {
            get {
                return ResourceManager.GetString("MoreLogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MoreSearchButton {
            get {
                return ResourceManager.GetString("MoreSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MoreSettingsButton {
            get {
                return ResourceManager.GetString("MoreSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string MoreTagsButton {
            get {
                return ResourceManager.GetString("MoreTagsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no due.
        /// </summary>
        public static string NoDueTasksHeader {
            get {
                return ResourceManager.GetString("NoDueTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string OverdueTasksHeader {
            get {
                return ResourceManager.GetString("OverdueTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to hub.
        /// </summary>
        public static string PinAppbar {
            get {
                return ResourceManager.GetString("PinAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string SyncAppbar {
            get {
                return ResourceManager.GetString("SyncAppbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string TaskCompleteButton {
            get {
                return ResourceManager.GetString("TaskCompleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskDetailsHeader {
            get {
                return ResourceManager.GetString("TaskDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string TaskListDetail {
            get {
                return ResourceManager.GetString("TaskListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string TaskNotesAddButton {
            get {
                return ResourceManager.GetString("TaskNotesAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string TaskNotesDeleteButton {
            get {
                return ResourceManager.GetString("TaskNotesDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string TaskNotesEditButton {
            get {
                return ResourceManager.GetString("TaskNotesEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string TaskNotesHeader {
            get {
                return ResourceManager.GetString("TaskNotesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postpone.
        /// </summary>
        public static string TaskPostponeButton {
            get {
                return ResourceManager.GetString("TaskPostponeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TasksHeader {
            get {
                return ResourceManager.GetString("TasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TaskTagsDetail {
            get {
                return ResourceManager.GetString("TaskTagsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string TaskURLDetail {
            get {
                return ResourceManager.GetString("TaskURLDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string TaskWhenDetail {
            get {
                return ResourceManager.GetString("TaskWhenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string TodayTasksHeader {
            get {
                return ResourceManager.GetString("TodayTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string TomorrowTasksHeader {
            get {
                return ResourceManager.GetString("TomorrowTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later this week.
        /// </summary>
        public static string WeekTasksHeader {
            get {
                return ResourceManager.GetString("WeekTasksHeader", resourceCulture);
            }
        }
    }
}
